#!/bin/bash

# Use: ./renew email@domain.se

set -e

if [ -z "$1" ]
  then
    echo "Missing e-mail as first argument."
    exit 1
fi

docker run -i --rm --name certbot \
  -v "/var/log/letsencrypt:/var/log/letsencrypt" \
  -v "/etc/letsencrypt:/etc/letsencrypt" \
  -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
  quay.io/letsencrypt/letsencrypt:latest \
  --webroot \
  --email $1 \
  --agree-tos \
  -w /etc/letsencrypt/webrootauth \
  renew
