#!/bin/bash

set -e

docker run -it --rm --name certbot \
  -v "/var/log/letsencrypt:/var/log/letsencrypt" \
  -v "/etc/letsencrypt:/etc/letsencrypt" \
  -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
  quay.io/letsencrypt/letsencrypt:latest \
  --webroot \
  --email fredrik@nody.se \
  --agree-tos \
  --non-interactive \
  -w /etc/letsencrypt/webrootauth \
  renew
