#!/bin/bash

set -e

docker run --rm --name letsencrypt \
  -v "/var/log/letsencrypt:/var/log/letsencrypt" \
  -v "/etc/letsencrypt:/etc/letsencrypt" \
  -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
  letsencrypt:latest \
  --webroot-path "/etc/letsencrypt/webrootauth" \
  -c "/webroot.ini" -d nody.se www.nody.se certonly
